import {
    INVALID_EMAIL_INPUT_STYLING,
    VALID_EMAIL_INPUT_STYLING,
    RESET_EMAIL_INSTRUCTIONS
} from './credentials';
export {
    VALID_EMAIL_INPUT_STYLING,
    INVALID_EMAIL_INPUT_STYLING,
    RESET_EMAIL_INSTRUCTIONS
};

