export const numbers = [
  { number: 1000000000000, text: 'trillion' },
  { number: 1000000000, text: 'billion' },
  { number: 1000000, text: 'million' },
  { number: 1000, text: 'thousand' },
  { number: 100, text: 'hundred' },
  { number: 90, text: 'ninety' },
  { number: 80, text: 'eighty' },
  { number: 70, text: 'seventy' },
  { number: 60, text: 'sixty' },
  { number: 50, text: 'fifty' },
  { number: 40, text: 'forty' },
  { number: 30, text: 'thirty' },
  { number: 20, text: 'twenty' },
  { number: 19, text: 'nineteen' },
  { number: 18, text: 'eighteen' },
  { number: 17, text: 'seventeen' },
  { number: 16, text: 'sixteen' },
  { number: 15, text: 'fifteen' },
  { number: 14, text: 'fourteen' },
  { number: 13, text: 'thirteen' },
  { number: 12, text: 'twelve' },
  { number: 11, text: 'eleven' },
  { number: 10, text: 'ten' },
  { number: 9, text: 'nine' },
  { number: 8, text: 'eight' },
  { number: 7, text: 'seven' },
  { number: 6, text: 'six' },
  { number: 5, text: 'five' },
  { number: 4, text: 'four' },
  { number: 3, text: 'three' },
  { number: 2, text: 'two' },
  { number: 1, text: 'one' },
  { number: 0, text: 'zero' },
];

export const andWord = 'and';
